[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  madhephaestus/ESP32Servo
  bblanchon/ArduinoJson@^7
  adafruit/Adafruit SSD1306
  adafruit/Adafruit GFX Library
  links2004/WebSockets
  adafruit/Adafruit PWM Servo Driver Library
  knolleary/PubSubClient
